### ISSUE TITLE
how to get the paper

### ISSUE THREAD

**Issue by imdoublecats** [yifliu3/EPT-Net#1]
thank you for your job，but i want to know how to get your paper

**Comment by yifliu3** [comment]
Thanks for your attention. The paper can be accessed once the paper is published by MICCAI.

**Comment by imdoublecats** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by imdoublecats** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
