### ISSUE TITLE
how to divide the whole brain vessels into multiple segments?

### ISSUE THREAD

**Issue by jianjun0407** [yifliu3/EPT-Net#3]
Thank you for your work and reply, and I have the following two questions to discuss with you:
(1)I have one person's cerebral vessel segmentation result, but the current network input is vessel segment, how do I divide the whole brain vessels into multiple segments?
(2)As for the calculation of Geodesic matrix, I tried the method of "Geodesics in heat", but due to the large amount of calculation, the speed is still very slow. Is there a faster calculation method?

**Comment by yifliu3** [comment]
Thanks for your attention! Here are the answers to your questions:
(1) In our paper we directly use the processed segments provided by the IntrA dataset, and the detailed procedure to get segments from reconstructed 3D models is shown in their GitHub repositories. I remember they're using one software named Amira, where segments can be divided manually.
(2) I think directly computing the geodesic matrix on the whole cerebral vessels may require a lot of time, while calculation on segments that only contain thousands of points is quick. Besides, you can try other algorithms from modern 3D processing libraries.

**Comment by jianjun0407** [comment]
Thanks for your reply and look forward to your paper.
