### ISSUE TITLE
Paper request

### ISSUE THREAD

**Issue by YoannPitarch** [yifliu3/EPT-Net#4]
Hi, 
I'm really impressed by the abstract of your paper. It actually perfectly fits what I am working on. 
Is it possible to get access of the full paper in order to understand your code please?
Thanks!

**Comment by yifliu3** [comment]
Hi,
Thanks for your interest. The paper has been published by Spring, and here is the url: https://link.springer.com/content/pdf/10.1007/978-3-031-16443-9_10.pdf
