### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by felipestrella** [yifliu3/EPT-Net#7]
hello, i was trying to run the model ,while i was able to run the training, it seems that there is a problem with the test.py. It uses an utils.tools function called cal_Iou_Acc_batch. this functions require 2 parameters but in the test.py you intruduce 3 parameters.
![error](https://user-images.githubusercontent.com/98059099/218222683-ca1b2548-8cb8-47f5-b191-282886423a5e.JPG)

also when calling IntrADataset class in test.py, there is no instance attribute called 'test_all'
![error2](https://user-images.githubusercontent.com/98059099/218223754-d8e6746e-8778-4340-9990-94bf1727f717.JPG)

**Comment by yifliu3** [comment]
Hi, 

sorry for the late reply. The error raises from imcompatible code versions, you can fix them by few modifications. Besides, I will re-organize the code later. Thanks for your useful feedback!
